/**
 * Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms
 * will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 */
public class P002 {

    public static int fib(int n) {

        int a = 0;
        int b = 1;

        for (int i = 0; i < n; i++) {
            int temp = a + b;
            a = b;
            b = temp;
        }

        return b;
    }

    public static void main(String[] args) {

        int result = 0;

        for (int i = 0; i < 50; i++) {
            int f = fib(i);

            if (f > 4000000) {
                break;
            }

            if (f % 2 == 0) {
                result += f;
            }
        }

        System.out.println("Answer: " + result);
    }
}
